AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Photo Album Cloud Formation Template
Resources:

  S3BucketFrontend:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: photoalbum-assignment-786543132
      WebsiteConfiguration:
        IndexDocument: index.html
    # DeletionPolicy: Retain

  S3BucketFrontendPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: photoalbum-assignment-786543132
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: 'arn:aws:s3:::photoalbum-assignment-786543132/*'

  S3BucketPhotos:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: photoalbum-assignment-2456789157
    # DeletionPolicy: Retain

  S3BucketPhotosPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: photoalbum-assignment-2456789157
      PolicyDocument:
        Version: 2012-10-17
        Id: Policy1617042593879
        Statement:
          - Sid: Stmt1617042588580
            Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: 'arn:aws:s3:::photoalbum-assignment-2456789157/*'

  LambdaIndexPhotos:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: index-photos-7654321 # new lambda function created by cloudformation
      Code:
        S3Bucket: 'csinowato-zipfilesforlambda'
        S3Key: 'index-photos-d0d77b61-93c8-4895-9858-e44fa4a5c6b0.zip'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::280139081269:role/service-role/index-photos-role-m7x8ov06'

  LambdaSearchPhotos:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: search-photos-7654321 # new lambda function created by cloudformation
      Code:
        S3Bucket: 'csinowato-zipfilesforlambda'
        S3Key: 'search-photos-59836dd9-e59a-492e-8559-9846edfbdd57.zip'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::280139081269:role/service-role/search-photos-role-uw4yywhg'

  APIGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PhotoAlbumAPI-Cloudformation # new REST API generated by cloudformation
      BodyS3Location:
        Bucket: 'csinowato-zipfilesforlambda' # location of API yaml file
        Key: 'AI Photo Search-dev-swagger.yaml'

  ElasticSearchPhotoSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '7.9'
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: 't3.small.elasticsearch'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
